language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install -r requirements.txt -r requirements-dev.txt

env:
  global:
  - PYPI_USER_NAME: "chaostoolkit"
  - secure: "gMJtlu91rxcBW3WzPKNQk9vKyETvB8wGvEIFlsttJwj8XNaNeAAZBMfIDuTgcqQkxSlMSHuyex5T62pm03Sa3bJMBjLwY3aIentdhUs82uiM6/TYrV6D8g8rqjeytolUOWJhJS5ozlOfO5BpQu7ehPifz5ADtZSKXIkoKVKIK+X1lKpfYsGJWNTnhcAV3vKkW8PQu5VwpU6D4n7f6VUInbl00W4cTY07QrigPOaXROmwKikEYtWhfpOqaA5EmAhiId80G/ZaeWKJabbkqeoSDOufZtN1EyifS7trkOi2+rufrJFFLpWDyTQrQbqlfjnb648AYqCSzNSYQUgYuq3TKSwKlTXorHfYYD3W5PAKqoNZSAnGrnBCvEWRPQNcxKcrWwj50jpKB3BGkicP2ocNaLL6/gBz0HC9kixvQ5i1cNfEP8MK5EM93HjFSv7PhDbqm4g7CGylXdWUOxTNPkNnPBazb8/hWhi3T8T8uOtdGHyk0ec/jWu6HAYxr48duvw+bibeH7xp5jd+4W3G0kRef+MHDlbA3t00hU0VoDv8MxnKFf5yEwC2Ro69S1gX/BMfYFUuHqUNlHZhsRoxb2qTYiaB86ktZCDOyICAHXcQl4veKNcels/1Rvw2GC8cCFiuxC0Ak8yfMsvVkqUy815za9qhIGwyXUez3CgKi/kHO1g="

script: 
  - bash ci.bash

notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
