name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  release-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel twine build
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python3 -m build
        twine upload dist/*
    # push artifacts for other jobs to use
    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: chaostoolkit-istio-packages
        path: dist/chaostoolkit*

  create-gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  upload-gh-release-assets:
    runs-on: ubuntu-latest
    needs:
      - create-gh-release
      - release-to-pypi
    steps:
      - name: Download pypi artifacts
        uses: actions/download-artifact@v2-preview
        with:
          name: chaostoolkit-istio-packages
          path: dist
      - name: Upload wheel & source dist to GH release
        uses: ncipollo/release-action@v1
        with:
          artifact: "dist/*.whl,dist/*.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
